// Generated by gencpp from file rm_msgs/CurrentSentryPosData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_CURRENTSENTRYPOSDATA_H
#define RM_MSGS_MESSAGE_CURRENTSENTRYPOSDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct CurrentSentryPosData_
{
  typedef CurrentSentryPosData_<ContainerAllocator> Type;

  CurrentSentryPosData_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
    }
  CurrentSentryPosData_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> const> ConstPtr;

}; // struct CurrentSentryPosData_

typedef ::rm_msgs::CurrentSentryPosData_<std::allocator<void> > CurrentSentryPosData;

typedef boost::shared_ptr< ::rm_msgs::CurrentSentryPosData > CurrentSentryPosDataPtr;
typedef boost::shared_ptr< ::rm_msgs::CurrentSentryPosData const> CurrentSentryPosDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::CurrentSentryPosData_<ContainerAllocator1> & lhs, const ::rm_msgs::CurrentSentryPosData_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::CurrentSentryPosData_<ContainerAllocator1> & lhs, const ::rm_msgs::CurrentSentryPosData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b81376c2774ff4f956e5110e01c9db26";
  }

  static const char* value(const ::rm_msgs::CurrentSentryPosData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb81376c2774ff4f9ULL;
  static const uint64_t static_value2 = 0x56e5110e01c9db26ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/CurrentSentryPosData";
  }

  static const char* value(const ::rm_msgs::CurrentSentryPosData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::rm_msgs::CurrentSentryPosData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CurrentSentryPosData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::CurrentSentryPosData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::CurrentSentryPosData_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_CURRENTSENTRYPOSDATA_H
